"""Curated profile metadata dictionary providing verified ages, origins, categories, and OnlyFans links."""

from typing import Any

KNOWN_PERFORMER_PROFILES: dict[str, dict[str, Any]] = {
    "Abella Danger": {
        "age": 28,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/abelladanger",
        "gender": "female",
        "videos": 996,
        "views": 1400000000,
    },
    "Alex Adams": {
        "age": 24,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/alexadams",
        "gender": "male",
        "videos": 319,
        "views": 1800000000,
    },
    "Johnny Sins": {
        "age": 45,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/johnnysins",
        "gender": "male",
        "videos": 991,
        "views": 2300000000,
    },
    "Lana Rhoades": {
        "age": 28,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/lanarhoades",
        "gender": "female",
        "videos": 391,
        "views": 1200000000,
    },
    "Riley Reid": {
        "age": 33,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/rileyreid",
        "gender": "female",
        "videos": 834,
        "views": 1500000000,
    },
    "Mia Khalifa": {
        "age": 31,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/miakhalifa",
        "gender": "female",
        "videos": 299,
        "views": 1200000000,
    },
    "James Deen": {
        "age": 38,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 1075,
        "views": 1600000000,
    },
    "Tony Profane": {
        "age": 36,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 543,
        "views": 2800000000,
    },
    "Mick Blue": {
        "age": 48,
        "country": "Austria",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 1296,
        "views": 1200000000,
    },
    "Tyler Nixon": {
        "age": 39,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 694,
        "views": 1400000000,
    },
    "Mark Rockwell": {
        "age": 35,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 312,
        "views": 1200000000,
    },
    "Johnny Castle": {
        "age": 44,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 1170,
        "views": 1200000000,
    },
    "Tony Rubino": {
        "age": 42,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 773,
        "views": 1200000000,
    },
    "Xander Corvus": {
        "age": 42,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": None,
        "gender": "male",
        "videos": 1030,
        "views": 1200000000,
    },
    "Angela White": {
        "age": 39,
        "country": "Australia",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/theangelawhite",
        "gender": "female",
        "videos": 820,
        "views": 950000000,
    },
    "Amouranth": {
        "age": 30,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/amouranth",
        "gender": "female",
        "videos": 412,
        "views": 820000000,
    },
    "Bhad Bhabie": {
        "age": 21,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/bhadbhabie",
        "gender": "female",
        "videos": 180,
        "views": 620000000,
    },
    "Corinna Kopf": {
        "age": 29,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/corinnakopf",
        "gender": "female",
        "videos": 240,
        "views": 780000000,
    },
    "Sophie Rain": {
        "age": 20,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/sophierain",
        "gender": "female",
        "videos": 95,
        "views": 450000000,
    },
    "Mia Malkova": {
        "age": 32,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/miamalkova",
        "gender": "female",
        "videos": 640,
        "views": 980000000,
    },
    "Kendra Lust": {
        "age": 45,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/kendralust",
        "gender": "female",
        "videos": 710,
        "views": 890000000,
    },
    "Eva Lovia": {
        "age": 35,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/evalovia",
        "gender": "female",
        "videos": 490,
        "views": 750000000,
    },
    "Lena Paul": {
        "age": 30,
        "country": "United States",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/lenapaul",
        "gender": "female",
        "videos": 520,
        "views": 810000000,
    },
    "Emily Willis": {
        "age": 25,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/emilywillis",
        "gender": "female",
        "videos": 380,
        "views": 920000000,
    },
    "Gabbie Carter": {
        "age": 24,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/gabbiecarter",
        "gender": "female",
        "videos": 290,
        "views": 670000000,
    },
    "Vina Sky": {
        "age": 25,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/vinasky",
        "gender": "female",
        "videos": 310,
        "views": 590000000,
    },
    "Kenzie Reeves": {
        "age": 27,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/kenziereeves",
        "gender": "female",
        "videos": 440,
        "views": 720000000,
    },
    "Adriana Chechik": {
        "age": 32,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/adrianachechik",
        "gender": "female",
        "videos": 810,
        "views": 990000000,
    },
    "Alina Lopez": {
        "age": 28,
        "country": "United States",
        "category": "Top Star",
        "onlyfans_url": "https://onlyfans.com/alinalopez",
        "gender": "female",
        "videos": 360,
        "views": 610000000,
    },
    "Autumn Falls": {
        "age": 24,
        "country": "United States",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/autumnfalls",
        "gender": "female",
        "videos": 280,
        "views": 890000000,
    },
    "Little Caprice": {
        "age": 35,
        "country": "Czech Republic",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/littlecaprice",
        "gender": "female",
        "videos": 520,
        "views": 640000000,
    },
    "Liya Silver": {
        "age": 24,
        "country": "Russia",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/liyasilver",
        "gender": "female",
        "videos": 310,
        "views": 580000000,
    },
    "Sweetie Fox": {
        "age": 23,
        "country": "Russia",
        "category": "New Star",
        "onlyfans_url": "https://onlyfans.com/sweetiefox",
        "gender": "female",
        "videos": 190,
        "views": 710000000,
    },
    "Eva Elfie": {
        "age": 24,
        "country": "Russia",
        "category": "OnlyFans Star",
        "onlyfans_url": "https://onlyfans.com/evaelfie",
        "gender": "female",
        "videos": 340,
        "views": 980000000,
    },
}
